version: '2'
services:
  odoo11:
    image: odoo:11
    container_name: odoov11
    depends_on:
      - db
    ports:
      - "8075:8069"
    volumes:
      - ./odoo:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    #environment:
    # - DB_PORT_5432_TCP_ADDR=db
    # - DB_PORT_5432_TCP_PORT=5432
    # - DB_ENV_POSTGRES_USER=odoo
    # - DB_ENV_POSTGRES_PASSWORD=odoo
  db:
    image: postgres:9.6
    container_name: db9.6
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ./data:/var/lib/postgresql/data/
